name: Validate json

"on":
  workflow_dispatch:
  push:
    paths:
      - 'extensions/**.json'
      - 'tags.json'
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    paths:
      - 'extensions/**.json'
      - 'tags.json'
      - 'index.json'

jobs:
  validate-json:
    strategy:
      matrix:
        python-version: ["3.10"]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3.4.0
      - uses: actions/setup-python@v4.5.0
        with:
          python-version: ${{ matrix.python-version }}

      - run: |
          python ./validate_json.py -i ./index.json
